/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard/invites'
import { Route as AppGoalsRouteImport } from './routes/app/goals'
import { Route as AppGoalIndexRouteImport } from './routes/app/goal/index'
import { Route as AppFriendsIndexRouteImport } from './routes/app/friends/index'
import { Route as DashboardGoalNewRouteImport } from './routes/dashboard/goal/new'
import { Route as DashboardFriendsUpdatesIndexRouteImport } from './routes/dashboard/friends/updates/index'
import { Route as AppFriendsUpdatesIndexRouteImport } from './routes/app/friends/updates/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalIndexRoute = AppGoalIndexRouteImport.update({
  id: '/goal/',
  path: '/goal/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsIndexRoute = AppFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DashboardGoalNewRoute = DashboardGoalNewRouteImport.update({
  id: '/goal/new',
  path: '/goal/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppFriendsInvitesRoute = AppFriendsInvitesRouteImport.update({
  id: '/friends/invites',
  path: '/friends/invites',
  getParentRoute: () => AppRouteRoute,
} as any)
const DashboardFriendsUpdatesIndexRoute =
  DashboardFriendsUpdatesIndexRouteImport.update({
    id: '/friends/updates/',
    path: '/friends/updates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AppFriendsUpdatesIndexRoute = AppFriendsUpdatesIndexRouteImport.update({
  id: '/friends/updates/',
  path: '/friends/updates/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/goal/new': typeof DashboardGoalNewRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/goal': typeof AppGoalIndexRoute
  '/app/friends/updates': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/goals': typeof AppGoalsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/app': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/goal/new': typeof DashboardGoalNewRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/goal': typeof AppGoalIndexRoute
  '/app/friends/updates': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/goal/new': typeof DashboardGoalNewRoute
  '/app/friends/': typeof AppFriendsIndexRoute
  '/app/goal/': typeof AppGoalIndexRoute
  '/app/friends/updates/': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates/': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/app/goals'
    | '/dashboard/invites'
    | '/dashboard/profile'
    | '/app/'
    | '/dashboard/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/goal/new'
    | '/app/friends'
    | '/app/goal'
    | '/app/friends/updates'
    | '/dashboard/friends/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/goals'
    | '/dashboard/invites'
    | '/dashboard/profile'
    | '/app'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/goal/new'
    | '/app/friends'
    | '/app/goal'
    | '/app/friends/updates'
    | '/dashboard/friends/updates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/app/goals'
    | '/dashboard/invites'
    | '/dashboard/profile'
    | '/app/'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/goal/new'
    | '/app/friends/'
    | '/app/goal/'
    | '/app/friends/updates/'
    | '/dashboard/friends/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goal/': {
      id: '/app/goal/'
      path: '/goal'
      fullPath: '/app/goal'
      preLoaderRoute: typeof AppGoalIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends/': {
      id: '/app/friends/'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dashboard/goal/new': {
      id: '/dashboard/goal/new'
      path: '/goal/new'
      fullPath: '/dashboard/goal/new'
      preLoaderRoute: typeof DashboardGoalNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/friends/updates/': {
      id: '/dashboard/friends/updates/'
      path: '/friends/updates'
      fullPath: '/dashboard/friends/updates'
      preLoaderRoute: typeof DashboardFriendsUpdatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/friends/updates/': {
      id: '/app/friends/updates/'
      path: '/friends/updates'
      fullPath: '/app/friends/updates'
      preLoaderRoute: typeof AppFriendsUpdatesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dashboard/friends/updates/': {
      id: '/dashboard/friends/updates/'
      path: '/friends/updates'
      fullPath: '/dashboard/friends/updates'
      preLoaderRoute: typeof DashboardFriendsUpdatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/friends/updates/': {
      id: '/app/friends/updates/'
      path: '/friends/updates'
      fullPath: '/app/friends/updates'
      preLoaderRoute: typeof AppFriendsUpdatesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppGoalsRoute: typeof AppGoalsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
  AppGoalIndexRoute: typeof AppGoalIndexRoute
  AppFriendsUpdatesIndexRoute: typeof AppFriendsUpdatesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGoalsRoute: AppGoalsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
  AppGoalIndexRoute: AppGoalIndexRoute,
  AppFriendsUpdatesIndexRoute: AppFriendsUpdatesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGoalNewRoute: typeof DashboardGoalNewRoute
  DashboardFriendsUpdatesIndexRoute: typeof DashboardFriendsUpdatesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGoalNewRoute: DashboardGoalNewRoute,
  DashboardFriendsUpdatesIndexRoute: DashboardFriendsUpdatesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
