/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard/invites'
import { Route as DashboardGoalsIndexRouteImport } from './routes/dashboard/goals/index'
import { Route as DashboardGoalsNewRouteImport } from './routes/dashboard/goals/new'
import { Route as DashboardFriendsUpdatesIndexRouteImport } from './routes/dashboard/friends/updates/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsIndexRoute = DashboardGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsNewRoute = DashboardGoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFriendsUpdatesIndexRoute =
  DashboardFriendsUpdatesIndexRouteImport.update({
    id: '/friends/updates/',
    path: '/friends/updates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/goals/new': typeof DashboardGoalsNewRoute
  '/dashboard/goals': typeof DashboardGoalsIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/goals/new': typeof DashboardGoalsNewRoute
  '/dashboard/goals': typeof DashboardGoalsIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/goals/new': typeof DashboardGoalsNewRoute
  '/dashboard/goals/': typeof DashboardGoalsIndexRoute
  '/dashboard/friends/updates/': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/invites'
    | '/dashboard/'
    | '/dashboard/goals/new'
    | '/dashboard/goals'
    | '/dashboard/friends/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/invites'
    | '/dashboard'
    | '/dashboard/goals/new'
    | '/dashboard/goals'
    | '/dashboard/friends/updates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/invites'
    | '/dashboard/'
    | '/dashboard/goals/new'
    | '/dashboard/goals/'
    | '/dashboard/friends/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals/': {
      id: '/dashboard/goals/'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals/new': {
      id: '/dashboard/goals/new'
      path: '/goals/new'
      fullPath: '/dashboard/goals/new'
      preLoaderRoute: typeof DashboardGoalsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/friends/updates/': {
      id: '/dashboard/friends/updates/'
      path: '/friends/updates'
      fullPath: '/dashboard/friends/updates'
      preLoaderRoute: typeof DashboardFriendsUpdatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGoalsNewRoute: typeof DashboardGoalsNewRoute
  DashboardGoalsIndexRoute: typeof DashboardGoalsIndexRoute
  DashboardFriendsUpdatesIndexRoute: typeof DashboardFriendsUpdatesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGoalsNewRoute: DashboardGoalsNewRoute,
  DashboardGoalsIndexRoute: DashboardGoalsIndexRoute,
  DashboardFriendsUpdatesIndexRoute: DashboardFriendsUpdatesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
