/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppGoalsRouteImport } from './routes/app/goals'
import { Route as AppGoalIndexRouteImport } from './routes/app/goal/index'
import { Route as AppFriendsIndexRouteImport } from './routes/app/friends/index'
import { Route as AppGoalNewRouteImport } from './routes/app/goal/new'
import { Route as AppFriendsInvitesRouteImport } from './routes/app/friends/invites'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalIndexRoute = AppGoalIndexRouteImport.update({
  id: '/goal/',
  path: '/goal/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsIndexRoute = AppFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalNewRoute = AppGoalNewRouteImport.update({
  id: '/goal/new',
  path: '/goal/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const DashboardFriendsUpdatesIndexRoute =
  DashboardFriendsUpdatesIndexRouteImport.update({
    id: '/friends/updates/',
    path: '/friends/updates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AppFriendsUpdatesIndexRoute = AppFriendsUpdatesIndexRouteImport.update({
  id: '/friends/updates/',
  path: '/friends/updates/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/app/goal/new': typeof AppGoalNewRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/goal': typeof AppGoalIndexRoute
  '/app/friends/updates': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/goals': typeof AppGoalsRoute
  '/app': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/app/goal/new': typeof AppGoalNewRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/goal': typeof AppGoalIndexRoute
  '/app/friends/updates': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/app/goals': typeof AppGoalsRoute
  '/app/': typeof AppIndexRoute
  '/app/friends/invites': typeof AppFriendsInvitesRoute
  '/app/goal/new': typeof AppGoalNewRoute
  '/app/friends/': typeof AppFriendsIndexRoute
  '/app/goal/': typeof AppGoalIndexRoute
  '/app/friends/updates/': typeof AppFriendsUpdatesIndexRoute
  '/dashboard/friends/updates/': typeof DashboardFriendsUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/app/goals'
    | '/app/'
    | '/app/friends/invites'
    | '/app/goal/new'
    | '/app/friends'
    | '/app/goal'
    | '/app/friends/updates'
    | '/dashboard/friends/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/goals'
    | '/app'
    | '/app/friends/invites'
    | '/app/goal/new'
    | '/app/friends'
    | '/app/goal'
    | '/app/friends/updates'
    | '/dashboard/friends/updates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/app/goals'
    | '/app/'
    | '/app/friends/invites'
    | '/app/goal/new'
    | '/app/friends/'
    | '/app/goal/'
    | '/app/friends/updates/'
    | '/dashboard/friends/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goal/': {
      id: '/app/goal/'
      path: '/goal'
      fullPath: '/app/goal'
      preLoaderRoute: typeof AppGoalIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends/': {
      id: '/app/friends/'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goal/new': {
      id: '/app/goal/new'
      path: '/goal/new'
      fullPath: '/app/goal/new'
      preLoaderRoute: typeof AppGoalNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends/invites': {
      id: '/app/friends/invites'
      path: '/friends/invites'
      fullPath: '/app/friends/invites'
      preLoaderRoute: typeof AppFriendsInvitesRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppGoalsRoute: typeof AppGoalsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFriendsInvitesRoute: typeof AppFriendsInvitesRoute
  AppGoalNewRoute: typeof AppGoalNewRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
  AppGoalIndexRoute: typeof AppGoalIndexRoute
  AppFriendsUpdatesIndexRoute: typeof AppFriendsUpdatesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGoalsRoute: AppGoalsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFriendsInvitesRoute: AppFriendsInvitesRoute,
  AppGoalNewRoute: AppGoalNewRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
  AppGoalIndexRoute: AppGoalIndexRoute,
  AppFriendsUpdatesIndexRoute: AppFriendsUpdatesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFriendsUpdatesIndexRoute: typeof DashboardFriendsUpdatesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFriendsUpdatesIndexRoute: DashboardFriendsUpdatesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
